title: CIT 281 Portfolio
description: Hi! My name is Lorena Garcia and this is my portfolio for CIT 281 with every lab and project I completed this term!
theme: jekyll-theme-argon #
header-img: back.png
