title: CIT 281 Portfolio
description: Hi! My name is Lorena Garcia and this is my portfolio for CIT 281 with every lab and project I completed this ter!
theme: jekyll-theme-cayman #
header-img: /imagegit.jpg
background-img: back.png
